-- GHARSEVA SUPABASE SETUP
-- Run this entire file in Supabase Dashboard > SQL Editor.
-- Then edit js/config.js with Project URL + anon/public key.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('customer','provider','admin')),
  full_name text not null,
  phone text,
  email text,
  address text,
  latitude double precision,
  longitude double precision,
  experience_years integer default 0,
  aadhaar_last4 text,
  verification_status text default 'pending',
  rating_avg numeric(3,2) default 0,
  created_at timestamptz default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text unique not null,
  icon text default '🛠️',
  description text,
  active boolean default true
);

create table if not exists public.provider_services (
  provider_id uuid references public.profiles(id) on delete cascade,
  service_id bigint references public.services(id) on delete cascade,
  primary key(provider_id,service_id)
);

create table if not exists public.service_requests (
  id bigint generated by default as identity primary key,
  customer_id uuid references public.profiles(id) on delete set null,
  provider_id uuid references public.profiles(id) on delete set null,
  service_id bigint references public.services(id) on delete set null,
  customer_latitude double precision,
  customer_longitude double precision,
  problem_description text,
  problem_media_path text,
  status text default 'pending' check(status in ('pending','accepted','rejected','completed','cancelled')),
  created_at timestamptz default now()
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  request_id bigint references public.service_requests(id) on delete cascade,
  customer_id uuid references public.profiles(id) on delete set null,
  provider_id uuid references public.profiles(id) on delete cascade,
  rating integer check(rating between 1 and 5),
  review_text text,
  created_at timestamptz default now()
);

insert into public.services(name,icon,description) values
('Electrician','🔌','Wiring, fan, switch, appliance work'),
('Plumber','🚰','Pipes, taps, leakage, bathroom'),
('Mason / Mistri','🧱','Construction, repair, plaster'),
('Labour','👷','Loading, shifting, general work'),
('Cleaning','🧹','Home, office and deep cleaning'),
('Toilet Cleaner','🚽','Bathroom and toilet cleaning'),
('Carpenter','🪚','Furniture, doors, wood work'),
('Painter','🎨','Wall, house and commercial painting'),
('Car Mechanic','🚗','Car repair and roadside help'),
('Bike Mechanic','🏍️','Bike service and repair'),
('AC Technician','❄️','AC service, repair and installation'),
('Appliance Repair','📱','TV, fridge, washing machine etc.'),
('RO Technician','🏠','RO/water purifier service'),
('Welder','🔧','Gate, grill and metal welding'),
('Gardener','🌿','Garden and plant maintenance'),
('Glass Worker','🪟','Glass, window and fitting work'),
('Packers & Movers','📦','Packing, loading and shifting'),
('Other Services','🛠️','More local services')
on conflict(name) do update set icon=excluded.icon,description=excluded.description;

create or replace function public.find_nearby_providers(
  p_service_id bigint,p_lat double precision,p_lng double precision,p_radius_km double precision default 25
)
returns table(provider_id uuid,full_name text,phone text,address text,experience_years integer,rating_avg numeric,verification_status text,distance_km double precision)
language sql stable security definer set search_path=public
as $$
select p.id,p.full_name,p.phone,p.address,p.experience_years,p.rating_avg,p.verification_status,
round((6371 * acos(least(1,greatest(-1,
cos(radians(p_lat))*cos(radians(p.latitude))*cos(radians(p.longitude)-radians(p_lng))
+sin(radians(p_lat))*sin(radians(p.latitude))
))))::numeric,2)::double precision
from public.profiles p
join public.provider_services ps on ps.provider_id=p.id
where p.role='provider' and p.verification_status='approved' and ps.service_id=p_service_id
and p.latitude is not null and p.longitude is not null
and (6371 * acos(least(1,greatest(-1,
cos(radians(p_lat))*cos(radians(p.latitude))*cos(radians(p.longitude)-radians(p_lng))
+sin(radians(p_lat))*sin(radians(p.latitude))
)))) <= p_radius_km
order by distance_km asc;
$$;

alter table public.profiles enable row level security;
alter table public.services enable row level security;
alter table public.provider_services enable row level security;
alter table public.service_requests enable row level security;
alter table public.reviews enable row level security;

drop policy if exists "public read active services" on public.services;
create policy "public read active services" on public.services for select using (active=true);

drop policy if exists "users read own profile" on public.profiles;
create policy "users read own profile" on public.profiles for select to authenticated using (auth.uid()=id);

drop policy if exists "users insert own profile" on public.profiles;
create policy "users insert own profile" on public.profiles for insert to authenticated with check (auth.uid()=id);

drop policy if exists "users update own profile" on public.profiles;
create policy "users update own profile" on public.profiles for update to authenticated using (auth.uid()=id) with check (auth.uid()=id);

drop policy if exists "providers read own expertise" on public.provider_services;
create policy "providers read own expertise" on public.provider_services for select to authenticated using (provider_id=auth.uid());

drop policy if exists "providers add own expertise" on public.provider_services;
create policy "providers add own expertise" on public.provider_services for insert to authenticated with check (provider_id=auth.uid());

drop policy if exists "customers create requests" on public.service_requests;
create policy "customers create requests" on public.service_requests for insert to authenticated with check (customer_id=auth.uid());

drop policy if exists "customers read own requests" on public.service_requests;
create policy "customers read own requests" on public.service_requests for select to authenticated using (customer_id=auth.uid());

drop policy if exists "providers read assigned requests" on public.service_requests;
create policy "providers read assigned requests" on public.service_requests for select to authenticated using (provider_id=auth.uid());

drop policy if exists "reviews public read" on public.reviews;
create policy "reviews public read" on public.reviews for select using (true);

-- IMPORTANT ADMIN SETUP:
-- 1) Register one normal account.
-- 2) Copy that user's UUID from Authentication > Users.
-- 3) Run:
-- update public.profiles set role='admin' where id='PASTE_USER_UUID_HERE';
-- Do NOT make your whole database public and do NOT expose service_role key.

-- OPTIONAL STORAGE:
-- Create a Storage bucket named "problem-media" in Storage.
-- Keep it private. Add authenticated-user policies through the Storage UI.
-- Do not upload/store full Aadhaar documents in this prototype.
